# Generated by Django 3.2.9 on 2021-12-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_auto_20211206_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='origin_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.originplace', verbose_name='產地'),
        ),
    ]
